# The Numpy Library

One of the most popular python libraries is `numpy`, which can be found in hundreds of other libraries.  NumPy takes advantage of the speed of C++ and FORTRAN code while being usable inside python, making it extremely powerful.  As their own website states, "A solution in NumPy is often clear and elegant".

We'll cover some of the basic or common functions below to get started, but keep in mind that there is quite a bit more that numpy can do to make your python-coding life easier.  NumPy has no dependencies outside of python itself.  It also comes standard with most python installations (like Anaconda).  Loading numpy is therefore simple.  The convention is to use the code below.

In [3]:
import numpy as np

NumPy is most often associated with the "numpy array", which is effectively a list of elements.  However, the `numpy` library takes the array to a higher level and has a lot more included functionality.  Let's look at how a basic array can be made with `numpy`.

In [8]:
my_array = np.arange(0,100)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


We can see the use of `np.arange` above.  It has two required arguments for the start and ending values.  Note that in the code above, the end value is 100, but the actual list stops at 99.  This means if you actually want 0 to 100, you should set an end value of 101.

We can also add a third value for stride, or how much to increment the value.

In [9]:
my_array = np.arange(0,100,5)
print(my_array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In the example above, we get values that are 5 apart.  If we adjust the end point to 101, we'll get the last value (100) as well.

If we want to get a range of values that are evenly spaced between two endpoints *and includes both of those endpoints*, we can use the `linspace` function.  The `linspace` function requires three values - start, end, and number of values to return.  It is important to keep in mind how the array is created in this function.  If a set of N values is requested between X and Y, it will calculate the increment as follows:

$$ I = \frac{Y-X}{N-1} $$

This will produce values of $[X, X+I, X+2I, ..., X+(N-1)I, Y]$, which are equally spaced.

The reason this is being explained is shown below.  If we wanted 20 values between 0 and 10, we might intuitively think it would give us increments of 0.5, so that the array would look like $[0,0.5,1.0,1.5,...]$.  However, the `linspace` array includes both endpoints in the list.

In [13]:
my_array = np.linspace(0,10,20)
print(my_array)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [14]:
my_array = np.linspace(0,10,21)
print(my_array)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


Another function in `numpy` is the `roll` function.  This treats the array like a closed loop and lets you move all elements some number of spaces down, looping end elements back to the start.

In [20]:
np.roll(my_array,1) # shift everything 1 space over, brings the last element to the front.

array([10. ,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,
        5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [19]:
np.roll(my_array,3) # Shift everything 3 spaces over.

array([ 9. ,  9.5, 10. ,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,
        4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5])

### numpy.linalg

NumPy has a number of submodules that are useful for certain tasks.  The `linalg` submodule is short for Linear Algebra, which is focused on vector-, matrix-, and tensor-math functions.  Most of the things you learn to calculate by hand in a multivariable calculus course can be done with simple functions in `numpy.linalg`

For example, if you have a vector $[1,2,3]$, you can get the magnitude of the vector by using `linalg.norm`.

In [21]:
import numpy.linalg as la

my_vector=[1,2,3]
print(la.norm(my_vector))

3.7416573867739413


You can also do more complicated operations like the dot-product or cross-products

#### np.dot()

In [25]:
vec1 = [1,2,3]
vec2 = [4,5,6]
dot_product = np.dot(vec1,vec2)
print(dot_product)

32


#### np.cross()

In [36]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[1,2],[3,4],[5,6]])
cross_product = np.cross(mat1,mat2)

print(mat1)
print(mat2)
print(cross_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [3 4]
 [5 6]]
[[ -6   3   0]
 [-24  18   1]
 [-54  45   2]]


### Random Number Generators

Numpy is also home to a good selection of random number generators that can provide different random distributions depending on what kind of random number you need.
- uniform
- normal (Gaussian)
- exponential
- binomial
- etc.

### Polynomial Fits

`numpy.polynomial` can provide you with data fitting tools to obtain $N$-degree polynomials for your data.
